version: "3"

services:
  postgres:
    hostname: postgres
    image: postgres:11-alpine
    env_file: 
      - ../engconfig/engconfig.env
    ports: 
      - "5432:5432"
  scraper:
    build: .
    image: hack4laengage/engage_scheduler:latest
    depends_on:
      - "postgres"
    env_file: 
      - ../engconfig/engconfig.env
    volumes: 
      - .:/engage-scraper
    links:
      - "postgres"
